name: 3 - Docker Build - ECS Service

on:
  push:
    branches:
      - develop
      - main

defaults:
  run:
    working-directory: docker

jobs:
  build-actions:
    name: Build Docker Image - ECS Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: develop - Set ENV to staging/demo
        if: endsWith(github.event.pull_request.base.ref, '/develop') || endsWith(github.ref, '/develop')
        run: echo '::set-output name=ENV::demo'

      - name: main - Set ENV to prod
        if: endsWith(github.event.pull_request.base.ref, '/main') || endsWith(github.ref, '/main')
        run: echo '::set-output name=ENV::prod'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Docker Image to ECR
        id: build-and-push
        run: make build-and-push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # Keep in sync with terraform/tf-aws-service/ecr.tf ecr->name
          ECR_REPOSITORY: ${{ env.ENV }}-${{ env.APP_NAME }}-ecr
          IMAGE_TAG: ${{ github.sha }}

      - name: Job Results
        shell: bash
        run: |
          echo fmt
          test ${{ steps.login-ecr.outputs.exitcode }} -eq 0
          echo init
          test ${{ steps.build-and-push.outputs.exitcode }} -eq 0