name: Terraform Destroy - Infrastructure

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: terraform/tf-aws-infra

jobs:
  tf_destroy:
    name: TF Destroy
    runs-on: ubuntu-latest

    steps:
      - name: develop - Set ENV to demo
        if: endsWith(github.ref, '/develop')
        run: echo '::set-output name=ENV::demo'

      - name: main - Set ENV to prod
        if: endsWith(github.ref, '/main')
        run: echo '::set-output name=ENV::prod'

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.3

      - name: Terraform Destroy
        id: destroy
        run: make tf-destroy
        continue-on-error: true

      - name: Job Results
        run: |
          echo apply
          test ${{ steps.destroy.outputs.exitcode }} -eq 0